# Generated by Django 3.1.5 on 2021-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('pret', models.IntegerField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
